### ISSUE TITLE
Remove randomization from otherwise deterministic algorithms

### ISSUE THREAD

**Issue by saraedum** [cddlib/cddlib#5]
SageMath needs to work around the fact that cddlib uses pseudo-random numbers. The problem is that srand()/rand() are not portable, i.e., srand() with the same seed produces different rand() outputs on
different platforms. So in particular putting the same data into cddlib produces different outputs on Solaris and Linux.

The question now is the following: Why do we need randomization at all in some places?

In cddio.c:
```
dd_MatrixPtr dd_MatrixNormalizedSortedCopy(dd_MatrixPtr M,dd_rowindex *newpos){
...
dd_RandomPermutation(roworder, m, 123);
...
}
```

That's a deterministic algorithm it seems. Do we need the dd_RandomPermutation call at all?

In cddcore.c:
```
void dd_ComputeRowOrderVector(dd_ConePtr cone) {
...
case dd_LexMin: case dd_MinCutoff: case dd_MixCutoff: case dd_MaxCutoff:
...
dd_RandomPermutation(cone->OrderVector, cone->m, cone->rseed)
...
}
```
 
Again, this appears to be unnecessary. Why do we need a pseudo-random permutation there?

**Comment by saraedum** [comment]
@vbraun, feel free to weigh in :)

**Comment by vbraun** [comment]
Its not just dead architectures either, OSX and Linux have a different rand()

**Comment by saraedum** [comment]
@komeifukuda Do you think we could drop the randomizations in these two places?

**Comment by komeifukuda** [comment]
We only need a uniformly random generator, as the expected behavior of a randomized algorithm is sometimes much more superior to a deterministic one.  What do you propose as a substitute?

**Comment by saraedum** [comment]
Something like PCG maybe? http://www.pcg-random.org/download.html

**Comment by saraedum** [comment]
Licensed under Apache 2.0 which is not GPL-2 compatible. I don't think we should relicense as GPL-3 just because of random numbers that we use quite trivially. The author had agreed a few years ago to dual-license with an MIT license it seems but that process has stalled apparently https://github.com/imneme/pcg-c-basic/pull/2.

**Comment by saraedum** [comment]
[splitmix64](http://xoroshiro.di.unimi.it/splitmix64.c) is public domain and seems to be [very reasonable](https://github.com/lemire/testingRNG) though that does not really matter here.

**Comment by komeifukuda** [comment]
By the way, randomization only affects the computational time but not the result.  So, it really does not matter if different platforms give different random permutations.  Also, only a few experts use this option because the default lexmin sorting of the input works better than the random ordering most of the time.  Can we just leave rand() as it is?

**Comment by komeifukuda** [comment]
I see your point.  There is no need to have different orderings of output when one computes with the same option on different platforms.

I realized that the random permutation is used also for the purpose of avoiding O(n^2) worst-case behavior of the quicksort.   Any reasonable random generator should work well for this purpose.

Since it is easy to replace rand() with a deterministic algorithm (one of the two mentioned above), we should do it.  Who is ready to do this revision?  I can do it but I am not familiar with GitHub, and thus may not post it properly.

**Comment by saraedum** [comment]
I'm working on it already :)
