### ISSUE TITLE
Properly implement cdd_both_reps

### ISSUE THREAD

**Issue by saraedum** [cddlib/cddlib#6]
See #3.

`cdd_both_reps.c` that a lot of distributions ship with cddlib has some performance issues it seems. We should try to implement it properly.

**Comment by saraedum** [comment]
I could imagine giving it a try if @komeifukuda could give me some hints on where to start.

**Comment by komeifukuda** [comment]
simplecdd.c does essentially the functionality of cdd_both_reps with options "--all" and "reps".  One just have to change I/O types (command argument to stream/stdout).   This is very easy.  The last option "--adjacency" requires a totally different computation (linear optimization) because it assumes that only one representation is known.  Note that when both representations are known, this is a simple combinatorial computation and thus has no extra cost.   I wonder if it makes sense to include the third option in the program called "cdd_both_reps."  It is much more natural to implement the last functionality separetely.  In fact, this is written in the program adjacency.c.

**Comment by komeifukuda** [comment]
The program lcdd.c works exactly like cdd_both_reps --reps.  Try
lcdd_gmp < cube8.ine
It does not output the adjacency of any representation.
So, one can start with lcdd.c, adding some part of simplecdd.c is another way to emulate cdd_both_reps with "--reps" and "--all" options.  By adding the core part of adjacency.c 
it would have all three functionalities.

**Comment by komeifukuda** [comment]
@saraedum What about calling a new program "cddexec"?  The cdd functionalities are not only
representation conversion.  By using proper option names, one can tell what it does, like
cddexec --reps
cddexec --adjacency
cddexec --repsplus (instead of --all)
cddexec --redcheck (removing redundancies)
etc.

**Comment by saraedum** [comment]
Ok. That sounds like a good idea to me.

**Comment by saraedum** [comment]
@komeifukuda That might be a stupid question, but if I wanted to mimic what `cdd_both_reps --all` does, I could run  `cddexec --rep` and then put the output into `cddexec --repall` and that should be faster than explicitly calling `cddexec --redcheck` on the input, right?

**Comment by komeifukuda** [comment]
It depends on the input.  When the dimension is small (3,4), your method of converting twice tend to be faster.  When the dimension is not too small (like 5 or more), and the redundancy is large, say, 90%,
the first execution with --rep might take a long time (5 min), while the redcheck execution is just a few seconds (3 sec).
Maybe I should post some interesting examples with huge redundancies to illustrate this.  I thought those examples redtest*.ine are included in examples-ine directory, but they are not there.

**Comment by komeifukuda** [comment]
Not everyone is interested in removing redundancy from the input.  So, either --rep or --repall is
what many people like to do.  If removing redundancy from input is important for the user, he/she
should run --recheck, not --rep & --repall, because, --redcheck returns exact information on which one is redundant and which one is essential (with information on how row numbers are modified in the nonredundant representation).  

When the input is large and there is no redundancy, the --redcheck computation can be very long relative to the conversion.  You can try
time ./cddexec_gmp --redcheck < cube8.ext
which takes over 10 seconds, while converting between cube8.ext <-> cube8.ine
takes very little time.

Rule of thumb?  I can try to write some sentences but it might fail badly on some examples.

**Comment by saraedum** [comment]
I see. It seems that in Sage the polyhedra are always assumed to be without redundancy. Sure, maybe often people do not care about that, but the interface currently makes this assumption and it's beyond the scope of just replacing `cdd_both_reps` to remove this assumption. So, yes a rule of thumb would be great :)

**Comment by komeifukuda** [comment]
Actually, the one execution of --repall does everything.  The incidence information of the input contains the redundancy/nonredundancy information.  The nonredundant ones are incident to a maximal set of output.  So, extracting only those rows and the associated adjacency should give the result.

Anyway, Sage interface should be more flexible and offer the user to see which input rows are redundant.  Without this flexibility, the user cannot analyse their date properly.  As a researcher on 
optimization and geometric computation, I do not see why only one pair of nonredundant representations is given to the user (who is typically a researcher).

**Comment by saraedum** [comment]
I don't know why Sage does not offer more flexibility here. I can only guess that not many people are using Sage for research in that area but that polyhedra were originally added as a means to solve some other mathematical problem that reduced to linear optimization.

**Comment by komeifukuda** [comment]
I guess it goes both ways.  If Sage does not provide more flexible options, only a few people find it useful, especially with a very slow response with cdd_both_reps.   Can you provide different functions in Sage such as --rep --repall --redcheck and --adjacency?  The user can decide what they want with their data.

**Comment by saraedum** [comment]
I agree. The areas where Sage is particularly weak are the way they are because not many people use them because they are particularly weak.
Currently, polyhedra in Sage make the assumption that their representation is non-redundant. I assume it would be easy to relax this condition and provide more general functionality for somebody who knows Sage and works on research in that area.

**Comment by komeifukuda** [comment]
I have just checked the Sage Reference Manual.  It seems that there are no optimization functions available.   Both TOPCOM (enumeration of triangulations) and Gfan (enumeration of Groebner bases) use cddlib's linear optimization codes.  I imagine that Sage that needed to incorporate these two codes leads to include cddlib.   I think the direct access to linear optimization of cddlib is useful for people who need an exact linear optimization.   The statistic package R has a very good interface to cddlib optimization.  Eventually, non-linear optimization codes might be useful for Sage, but the nonexactness of most nonlinear optimization algorithms can be a serious issue.
