### ISSUE TITLE
Difference between GMPFLOAT and GMPRATIONAL in cddmp.h

### ISSUE THREAD

**Issue by JacksonZyy** [cddlib/cddlib#65]
Hi,

I noticed both GMPFLOAT and GMPRATIONAL in cddmp.h.
May I ask what is the difference between these two? And also how can I compile with GMP float option perhaps?
Thanks for your reply!

**Comment by saraedum** [comment]
Just from looking at the code, it seems that GMPFLOAT is not really supported in the build system at the moment. If you search for `DGMPRATIONAL` you should find the place in the build system where GMPRATIONAL is selected.

It seems that when GMPFLOAT is set, we are using [mpf_t](https://gmplib.org/manual/Floating_002dpoint-Functions) instead of mpq_t. I am not sure how well this works and whether this works at all. (As I said, I am just guessing here by looking at the code.)

**Comment by JacksonZyy** [comment]
Hi,

Thanks for your reply, I tried with GMPFLOAT, it doesn't really work.

BTW, I have [Numerically inconsistent](https://github.com/cddlib/cddlib/issues/34#) problem during execution, I tried to remove the redundancy points in V-representation (or adjust almostzero), but still led to this problem.
Does this inconsistency (with no redundancy in input V-rep) happen within the computation, and there is nothing much that can be done to help? (GMP exact is too costly to be considered) Thank you.

**Comment by saraedum** [comment]
Ok. Then we should maybe remove the GMPFLOAT code path.

I don't know the answer to your question since I don't really know much about the inner workings of cddlib.

Maybe @komeifukuda colud weigh in?

**Comment by komeif** [comment]
@saraedum @JacksonZyy You are right that GMPFLOAT is not used in the build system.

It is there for the future project.  It is not meant to be a replacement of GMPRATIONAL, but it is
meant to be a replacement of the CPU dependent float arithmetic.  Sorry, I have not done any
further study myself.  I wanted to test GMPFLOAT against the CPU dependent float.  For this,
one has to define the precision and the associate constant when GMPFLOAT is used.
#define dd_almostzero  1.0E-7
in cdd.h.  So, currently, the implementation is incomplete, but it should be able to
function with a few more lines of code.

Instead of deleting GMPFLOAT, we might document the status of this arithmetic option. 
One major advantage of cddlib over all existing competing programs is that cddlib can use
different arithmetic very easily.  The cddlib is typically slower than the best programs because
of this arithmetic flexibility.  In cddlib, every single arithmetic operation is a functional call
that has an obvious overhead.

My original hope for cddlib is that we can do "real" arithmetic correctly, or more modestly,
do approximately correctly to guess the right answer when the input is irrational.
So, some floating arithmetic like GMPFLOAT with (machine independent) controlled error 
arithmetic might give some reasonable outcome. 

Clearly, my intention should have been documented in the distribution.

Thank you for pointing out the mysterious problem that should not have been a mystery.

**Comment by komeif** [comment]
@JacksonZyy To improve the efficiency of removing redundancy, please look at my recent experiments on Clarkson's algorithm:
https://cddlib.github.io/polyhedral_faq/#x1-230002.20
There are comparisons in both float and gmp arithmetics.  When the redundancy is huge, the speedup is very large.  It works only for full dimensional H-inputs at the moment.  For full dimensional V-inputs, the transformation to a full dimensional H-inputs is rather routine.  See Chap 7 of my textbook:
https://www.research-collection.ethz.ch/handle/20.500.11850/426218

**Comment by JacksonZyy** [comment]
@komeif Thank you so much for the information!
